version: "2.1"

services:
  # https://hub.docker.com/r/fireflyiii/core
  app:
    image: fireflyiii/core:version-5.7.5
    volumes:
      - upload:/var/www/html/storage/upload
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=firefly
      - DB_USERNAME=firefly
      - DB_PASSWORD=firefly
      - TRUSTED_PROXIES=**
    ports:
      - 80:8080
    depends_on:
      - db
    command: php artisan key:generate

  # https://hub.docker.com/r/yobasystems/alpine-mariadb
  db:
    image: yobasystems/alpine-mariadb:10.6.7
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=firefly
      - MYSQL_USER=firefly
      - MYSQL_PASSWORD=firefly
    # Repurpose the healthcheck cmd by having it export our database on a schedule.
    # Run the backup every 1 hour to a file called $MYSQL_DATABASE-dump.sql.
    # How to restore: <https://mariadb.com/kb/en/mysqldump/#restoring>
    healthcheck:
      test: mysqldump $MYSQL_DATABASE -u$MYSQL_USER -p$MYSQL_PASSWORD --result-file=/var/lib/mysql/$MYSQL_DATABASE-dump.sql || exit 0
      interval: 1h
      timeout: 30s
      retries: 3

  # https://hub.docker.com/r/fireflyiii/data-importer
  fidi:
    image: fireflyiii/data-importer:version-0.9.10
    environment:
      - FIREFLY_III_URL=http://app:8080
    ports:
      - 8081:8080
    depends_on:
      - app

  # https://github.com/balenablocks/hostname
  hostname:
    image: balenablocks/hostname
    restart: no
    labels:
      io.balena.features.supervisor-api: 1
    environment:
      SET_HOSTNAME: firefly

volumes:
  upload:
  db:
